### ISSUE TITLE
侧栏的链接都点不开

### ISSUE THREAD

**Issue by ICyChain** [shaunyoung-11/18px-Typecho-Theme#1]
http://blog.icychain1211.cf/

**Comment by suenyiyang** [comment]
您需要将主题文件夹名称命名为18px哦，您现在命名为18px-Typecho-Theme-master，有一个关键index.js我用的相对路径，那个会加载不出来，没法给侧边栏加动效，所以侧边栏会被一个遮罩覆盖，因此链接点不到。您将主题文件夹名称命名为18px试一下😄

**Comment by ICyChain** [comment]
可以加个微信吗？我想请教一下，这个主题太对我胃口了！
my wechat : icychain1211




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shuan Young"<notifications@github.com&gt;; 
发送时间: 2020年8月17日(星期一) 上午10:08
收件人: "shaunyoung-11/18px-Typecho-Theme"<18px-Typecho-Theme@noreply.github.com&gt;; 
抄送: "I.Cy-Chain不吝"<1378260632@QQ.COM&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shaunyoung-11/18px-Typecho-Theme] 侧栏的链接都点不开 (#1)





 
您需要将主题文件夹名称命名为18px哦，您现在命名为18px-Typecho-Theme-master，有一个关键index.js我用的相对路径，那个会加载不出来，没法给侧边栏加动效，所以侧边栏会被一个遮罩覆盖，因此链接点不到。您将主题文件夹名称命名为18px试一下😄

**Comment by suenyiyang** [comment]
发送验证申请了👌
